#ifndef __UTOOLS_USER_CFG_H__
#define __UTOOLS_USER_CFG_H__

// 开始稳定间隔调用器
#define UTOOLS_STABLE_INTERVAL_INVOKER_ENABLE UTOOLS_TRUE

// 开启同步队列
#define UTOOLS_COLLAB_SYNC_QUEUE_ENABLE UTOOLS_TRUE

// 日志功能
#define UTOOLS_LOGGER_ENABLE UTOOLS_TRUE
#define UTOOLS_LOGGER_ASYNC_ENABLE UTOOLS_TRUE

// 协同任务功能中的函数包装器,用于生成c的函数指针
// #define UTOOLS_COLLAB_FUNC_WRAPPER_ENABLE UTOOLS_TRUE

// 使用CMSIS_V2系统，嵌入式系统平台为STM32
#define UTOOLS_OS_TYPE UTOOLS_OS_TYPE_FREERTOS
#define UTOOLS_EMBEDDED_PLATFORM UTOOLS_EMBEDDED_PLATFORM_STM32
#define UTOOLS_COLLAB_TASK_ENABLE UTOOLS_TRUE               // Task任务功能
#define UTOOLS_COLLAB_TASK_POOL_ENABLE UTOOLS_TRUE          // 任务池功能
#define UTOOLS_COLLAB_TASK_STACK_DEFAULT_SIZE ((size_t)512) // 默认任务栈大小
#define UTOOLS_COLLAB_TIMER_ENABLE UTOOLS_TRUE              // 定时器功能

// 提供_gettopic_time函数功能
#define UTOOLS_NEWLIB__GETTOPICTIME_ENABLE UTOOLS_TRUE

// 关于功能，提供版本管理器
#define UTOOLS_ABOUT_ENABLE UTOOLS_TRUE

// 代码字节功能，ByteStruct
#define UTOOLS_BYTES_STRUCT_ENABLE UTOOLS_TRUE

// 异步订阅与发布功能
#define UTOOLS_ASYNC_PUBSUB_ENABLE UTOOLS_TRUE

#define UTOOLS_SYNC_PUBSUB_ENABLE UTOOLS_TRUE

#define UTOOLS_PUBSUB_ENABLE UTOOLS_TRUE

#endif // __UTOOLS_USER_CFG_H__
