##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = h743ii_lcd


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/KD024VGFPD094.c \
Core/Src/dma2d.c \
Core/Src/fmc.c \
Core/Src/freertos.c \
Core/Src/gpio.c \
Core/Src/i2c.c \
Core/Src/lcd_fonts.c \
Core/Src/lcd_image.c \
Core/Src/lcd_rgb.c \
Core/Src/lcd_test.c \
Core/Src/ltdc.c \
Core/Src/stm32h7xx_hal_msp.c \
Core/Src/stm32h7xx_hal_timebase_tim.c \
Core/Src/stm32h7xx_it.c \
Core/Src/syscalls.c \
Core/Src/sysmem.c \
Core/Src/system_stm32h7xx.c \
Core/Src/tim.c \
Core/Src/usart.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma2d.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sdram.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_fmc.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
User/config/lvgl/lv_port_disp.c \
User/lib/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_alpha16.c \
User/lib/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_argb.c \
User/lib/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_chroma_keyed.c \
User/lib/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_indexed16.c \
User/lib/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_rgb.c \
User/lib/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_rgb565a8.c \
User/lib/lvgl/demos/benchmark/assets/lv_font_bechmark_montserrat_12_compr_az.c.c \
User/lib/lvgl/demos/benchmark/assets/lv_font_bechmark_montserrat_16_compr_az.c.c \
User/lib/lvgl/demos/benchmark/assets/lv_font_bechmark_montserrat_28_compr_az.c.c \
User/lib/lvgl/demos/benchmark/lv_demo_benchmark.c \
User/lib/lvgl/demos/keypad_encoder/lv_demo_keypad_encoder.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_corner_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_list_play.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_list_play_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_loop.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_loop_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_next.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_next_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_pause.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_pause_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_play.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_play_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_prev.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_prev_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_rnd.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_btn_rnd_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_corner_left.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_corner_left_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_corner_right.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_corner_right_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_cover_1.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_cover_1_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_cover_2.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_cover_2_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_cover_3.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_cover_3_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_icon_1.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_icon_1_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_icon_2.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_icon_2_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_icon_3.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_icon_3_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_icon_4.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_icon_4_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_list_border.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_list_border_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_logo.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_slider_knob.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_slider_knob_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_wave_bottom.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_wave_bottom_large.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_wave_top.c \
User/lib/lvgl/demos/music/assets/img_lv_demo_music_wave_top_large.c \
User/lib/lvgl/demos/music/lv_demo_music.c \
User/lib/lvgl/demos/music/lv_demo_music_list.c \
User/lib/lvgl/demos/music/lv_demo_music_main.c \
User/lib/lvgl/demos/stress/lv_demo_stress.c \
User/lib/lvgl/demos/widgets/assets/img_clothes.c \
User/lib/lvgl/demos/widgets/assets/img_demo_widgets_avatar.c \
User/lib/lvgl/demos/widgets/assets/img_lvgl_logo.c \
User/lib/lvgl/demos/widgets/lv_demo_widgets.c \
User/lib/lvgl/env_support/rt-thread/lv_rt_thread_port.c \
User/lib/lvgl/env_support/rt-thread/squareline/lv_ui_entry.c \
User/lib/lvgl/src/core/lv_disp.c \
User/lib/lvgl/src/core/lv_event.c \
User/lib/lvgl/src/core/lv_group.c \
User/lib/lvgl/src/core/lv_indev.c \
User/lib/lvgl/src/core/lv_indev_scroll.c \
User/lib/lvgl/src/core/lv_obj.c \
User/lib/lvgl/src/core/lv_obj_class.c \
User/lib/lvgl/src/core/lv_obj_draw.c \
User/lib/lvgl/src/core/lv_obj_pos.c \
User/lib/lvgl/src/core/lv_obj_scroll.c \
User/lib/lvgl/src/core/lv_obj_style.c \
User/lib/lvgl/src/core/lv_obj_style_gen.c \
User/lib/lvgl/src/core/lv_obj_tree.c \
User/lib/lvgl/src/core/lv_refr.c \
User/lib/lvgl/src/core/lv_theme.c \
User/lib/lvgl/src/draw/arm2d/lv_gpu_arm2d.c \
User/lib/lvgl/src/draw/lv_draw.c \
User/lib/lvgl/src/draw/lv_draw_arc.c \
User/lib/lvgl/src/draw/lv_draw_img.c \
User/lib/lvgl/src/draw/lv_draw_label.c \
User/lib/lvgl/src/draw/lv_draw_layer.c \
User/lib/lvgl/src/draw/lv_draw_line.c \
User/lib/lvgl/src/draw/lv_draw_mask.c \
User/lib/lvgl/src/draw/lv_draw_rect.c \
User/lib/lvgl/src/draw/lv_draw_transform.c \
User/lib/lvgl/src/draw/lv_draw_triangle.c \
User/lib/lvgl/src/draw/lv_img_buf.c \
User/lib/lvgl/src/draw/lv_img_cache.c \
User/lib/lvgl/src/draw/lv_img_decoder.c \
User/lib/lvgl/src/draw/nxp/pxp/lv_draw_pxp.c \
User/lib/lvgl/src/draw/nxp/pxp/lv_draw_pxp_blend.c \
User/lib/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp.c \
User/lib/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp_osa.c \
User/lib/lvgl/src/draw/nxp/vglite/lv_draw_vglite.c \
User/lib/lvgl/src/draw/nxp/vglite/lv_draw_vglite_arc.c \
User/lib/lvgl/src/draw/nxp/vglite/lv_draw_vglite_blend.c \
User/lib/lvgl/src/draw/nxp/vglite/lv_draw_vglite_line.c \
User/lib/lvgl/src/draw/nxp/vglite/lv_draw_vglite_rect.c \
User/lib/lvgl/src/draw/nxp/vglite/lv_vglite_buf.c \
User/lib/lvgl/src/draw/nxp/vglite/lv_vglite_utils.c \
User/lib/lvgl/src/draw/renesas/lv_gpu_d2_draw_label.c \
User/lib/lvgl/src/draw/renesas/lv_gpu_d2_ra6m3.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_arc.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_bg.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_composite.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_img.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_label.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_layer.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_line.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_mask.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_polygon.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_rect.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_stack_blur.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_texture_cache.c \
User/lib/lvgl/src/draw/sdl/lv_draw_sdl_utils.c \
User/lib/lvgl/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_arc.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_blend.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_dither.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_gradient.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_img.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_layer.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_letter.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_line.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_polygon.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_rect.c \
User/lib/lvgl/src/draw/sw/lv_draw_sw_transform.c \
User/lib/lvgl/src/draw/swm341_dma2d/lv_gpu_swm341_dma2d.c \
User/lib/lvgl/src/extra/layouts/flex/lv_flex.c \
User/lib/lvgl/src/extra/layouts/grid/lv_grid.c \
User/lib/lvgl/src/extra/libs/bmp/lv_bmp.c \
User/lib/lvgl/src/extra/libs/ffmpeg/lv_ffmpeg.c \
User/lib/lvgl/src/extra/libs/freetype/lv_freetype.c \
User/lib/lvgl/src/extra/libs/fsdrv/lv_fs_fatfs.c \
User/lib/lvgl/src/extra/libs/fsdrv/lv_fs_littlefs.c \
User/lib/lvgl/src/extra/libs/fsdrv/lv_fs_posix.c \
User/lib/lvgl/src/extra/libs/fsdrv/lv_fs_stdio.c \
User/lib/lvgl/src/extra/libs/fsdrv/lv_fs_win32.c \
User/lib/lvgl/src/extra/libs/gif/gifdec.c \
User/lib/lvgl/src/extra/libs/gif/lv_gif.c \
User/lib/lvgl/src/extra/libs/png/lodepng.c \
User/lib/lvgl/src/extra/libs/png/lv_png.c \
User/lib/lvgl/src/extra/libs/qrcode/lv_qrcode.c \
User/lib/lvgl/src/extra/libs/qrcode/qrcodegen.c \
User/lib/lvgl/src/extra/libs/rlottie/lv_rlottie.c \
User/lib/lvgl/src/extra/libs/sjpg/lv_sjpg.c \
User/lib/lvgl/src/extra/libs/sjpg/tjpgd.c \
User/lib/lvgl/src/extra/libs/tiny_ttf/lv_tiny_ttf.c \
User/lib/lvgl/src/extra/lv_extra.c \
User/lib/lvgl/src/extra/others/fragment/lv_fragment.c \
User/lib/lvgl/src/extra/others/fragment/lv_fragment_manager.c \
User/lib/lvgl/src/extra/others/gridnav/lv_gridnav.c \
User/lib/lvgl/src/extra/others/ime/lv_ime_pinyin.c \
User/lib/lvgl/src/extra/others/imgfont/lv_imgfont.c \
User/lib/lvgl/src/extra/others/monkey/lv_monkey.c \
User/lib/lvgl/src/extra/others/msg/lv_msg.c \
User/lib/lvgl/src/extra/others/snapshot/lv_snapshot.c \
User/lib/lvgl/src/extra/themes/basic/lv_theme_basic.c \
User/lib/lvgl/src/extra/themes/default/lv_theme_default.c \
User/lib/lvgl/src/extra/themes/mono/lv_theme_mono.c \
User/lib/lvgl/src/extra/widgets/animimg/lv_animimg.c \
User/lib/lvgl/src/extra/widgets/calendar/lv_calendar.c \
User/lib/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.c \
User/lib/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.c \
User/lib/lvgl/src/extra/widgets/chart/lv_chart.c \
User/lib/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.c \
User/lib/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.c \
User/lib/lvgl/src/extra/widgets/keyboard/lv_keyboard.c \
User/lib/lvgl/src/extra/widgets/led/lv_led.c \
User/lib/lvgl/src/extra/widgets/list/lv_list.c \
User/lib/lvgl/src/extra/widgets/menu/lv_menu.c \
User/lib/lvgl/src/extra/widgets/meter/lv_meter.c \
User/lib/lvgl/src/extra/widgets/msgbox/lv_msgbox.c \
User/lib/lvgl/src/extra/widgets/span/lv_span.c \
User/lib/lvgl/src/extra/widgets/spinbox/lv_spinbox.c \
User/lib/lvgl/src/extra/widgets/spinner/lv_spinner.c \
User/lib/lvgl/src/extra/widgets/tabview/lv_tabview.c \
User/lib/lvgl/src/extra/widgets/tileview/lv_tileview.c \
User/lib/lvgl/src/extra/widgets/win/lv_win.c \
User/lib/lvgl/src/font/lv_font.c \
User/lib/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
User/lib/lvgl/src/font/lv_font_fmt_txt.c \
User/lib/lvgl/src/font/lv_font_loader.c \
User/lib/lvgl/src/font/lv_font_montserrat_10.c \
User/lib/lvgl/src/font/lv_font_montserrat_12.c \
User/lib/lvgl/src/font/lv_font_montserrat_12_subpx.c \
User/lib/lvgl/src/font/lv_font_montserrat_14.c \
User/lib/lvgl/src/font/lv_font_montserrat_16.c \
User/lib/lvgl/src/font/lv_font_montserrat_18.c \
User/lib/lvgl/src/font/lv_font_montserrat_20.c \
User/lib/lvgl/src/font/lv_font_montserrat_22.c \
User/lib/lvgl/src/font/lv_font_montserrat_24.c \
User/lib/lvgl/src/font/lv_font_montserrat_26.c \
User/lib/lvgl/src/font/lv_font_montserrat_28.c \
User/lib/lvgl/src/font/lv_font_montserrat_28_compressed.c \
User/lib/lvgl/src/font/lv_font_montserrat_30.c \
User/lib/lvgl/src/font/lv_font_montserrat_32.c \
User/lib/lvgl/src/font/lv_font_montserrat_34.c \
User/lib/lvgl/src/font/lv_font_montserrat_36.c \
User/lib/lvgl/src/font/lv_font_montserrat_38.c \
User/lib/lvgl/src/font/lv_font_montserrat_40.c \
User/lib/lvgl/src/font/lv_font_montserrat_42.c \
User/lib/lvgl/src/font/lv_font_montserrat_44.c \
User/lib/lvgl/src/font/lv_font_montserrat_46.c \
User/lib/lvgl/src/font/lv_font_montserrat_48.c \
User/lib/lvgl/src/font/lv_font_montserrat_8.c \
User/lib/lvgl/src/font/lv_font_simsun_16_cjk.c \
User/lib/lvgl/src/font/lv_font_unscii_16.c \
User/lib/lvgl/src/font/lv_font_unscii_8.c \
User/lib/lvgl/src/hal/lv_hal_disp.c \
User/lib/lvgl/src/hal/lv_hal_indev.c \
User/lib/lvgl/src/hal/lv_hal_tick.c \
User/lib/lvgl/src/misc/lv_anim.c \
User/lib/lvgl/src/misc/lv_anim_timeline.c \
User/lib/lvgl/src/misc/lv_area.c \
User/lib/lvgl/src/misc/lv_async.c \
User/lib/lvgl/src/misc/lv_bidi.c \
User/lib/lvgl/src/misc/lv_color.c \
User/lib/lvgl/src/misc/lv_fs.c \
User/lib/lvgl/src/misc/lv_gc.c \
User/lib/lvgl/src/misc/lv_ll.c \
User/lib/lvgl/src/misc/lv_log.c \
User/lib/lvgl/src/misc/lv_lru.c \
User/lib/lvgl/src/misc/lv_math.c \
User/lib/lvgl/src/misc/lv_mem.c \
User/lib/lvgl/src/misc/lv_printf.c \
User/lib/lvgl/src/misc/lv_style.c \
User/lib/lvgl/src/misc/lv_style_gen.c \
User/lib/lvgl/src/misc/lv_templ.c \
User/lib/lvgl/src/misc/lv_timer.c \
User/lib/lvgl/src/misc/lv_tlsf.c \
User/lib/lvgl/src/misc/lv_txt.c \
User/lib/lvgl/src/misc/lv_txt_ap.c \
User/lib/lvgl/src/misc/lv_utils.c \
User/lib/lvgl/src/widgets/lv_arc.c \
User/lib/lvgl/src/widgets/lv_bar.c \
User/lib/lvgl/src/widgets/lv_btn.c \
User/lib/lvgl/src/widgets/lv_btnmatrix.c \
User/lib/lvgl/src/widgets/lv_canvas.c \
User/lib/lvgl/src/widgets/lv_checkbox.c \
User/lib/lvgl/src/widgets/lv_dropdown.c \
User/lib/lvgl/src/widgets/lv_img.c \
User/lib/lvgl/src/widgets/lv_label.c \
User/lib/lvgl/src/widgets/lv_line.c \
User/lib/lvgl/src/widgets/lv_objx_templ.c \
User/lib/lvgl/src/widgets/lv_roller.c \
User/lib/lvgl/src/widgets/lv_slider.c \
User/lib/lvgl/src/widgets/lv_switch.c \
User/lib/lvgl/src/widgets/lv_table.c \
User/lib/lvgl/src/widgets/lv_textarea.c \
User/lib/lvgl/tests/makefile/test.c \
User/lib/lvgl/tests/src/lv_test_indev.c \
User/lib/lvgl/tests/src/lv_test_init.c \
User/lib/lvgl/tests/src/test_cases/_test_template.c \
User/lib/lvgl/tests/src/test_cases/test_arc.c \
User/lib/lvgl/tests/src/test_cases/test_bar.c \
User/lib/lvgl/tests/src/test_cases/test_checkbox.c \
User/lib/lvgl/tests/src/test_cases/test_config.c \
User/lib/lvgl/tests/src/test_cases/test_demo_stress.c \
User/lib/lvgl/tests/src/test_cases/test_demo_widgets.c \
User/lib/lvgl/tests/src/test_cases/test_dropdown.c \
User/lib/lvgl/tests/src/test_cases/test_event.c \
User/lib/lvgl/tests/src/test_cases/test_font_loader.c \
User/lib/lvgl/tests/src/test_cases/test_fs.c \
User/lib/lvgl/tests/src/test_cases/test_line.c \
User/lib/lvgl/tests/src/test_cases/test_mem.c \
User/lib/lvgl/tests/src/test_cases/test_obj_tree.c \
User/lib/lvgl/tests/src/test_cases/test_screen_load.c \
User/lib/lvgl/tests/src/test_cases/test_slider.c \
User/lib/lvgl/tests/src/test_cases/test_snapshot.c \
User/lib/lvgl/tests/src/test_cases/test_style.c \
User/lib/lvgl/tests/src/test_cases/test_switch.c \
User/lib/lvgl/tests/src/test_cases/test_table.c \
User/lib/lvgl/tests/src/test_cases/test_textarea.c \
User/lib/lvgl/tests/src/test_cases/test_tiny_ttf.c \
User/lib/lvgl/tests/src/test_cases/test_txt.c \
User/lib/lvgl/tests/src/test_fonts/font_1.c \
User/lib/lvgl/tests/src/test_fonts/font_2.c \
User/lib/lvgl/tests/src/test_fonts/font_3.c \
User/lib/lvgl/tests/src/test_fonts/ubuntu_font.c \
User/lib/lvgl/tests/unity/unity.c \
User/lib/lvgl/tests/unity/unity_support.c \
User/module/ui/components/ui_comp_hook.c \
User/module/ui/images/ui_img_battery2_png.c \
User/module/ui/images/ui_img_motor_disconnected_png.c \
User/module/ui/images/ui_img_single6_png.c \
User/module/ui/images/ui_img_ue_png.c \
User/module/ui/screens/ui_Screen1.c \
User/module/ui/screens/ui_Screen2.c \
User/module/ui/ui.c \
User/module/ui/ui_helpers.c \
User/router/crouter.c


CPP_SOURCES = \
User/app_entry.cpp \
User/lib/sdcp/src/sdcp.cpp \
User/lib/sdcp/src/sdcp_impl.cpp \
User/lib/sdcp/src/sdcp_shcfg.cpp \
User/lib/simple_protocol/src/simple_protocol.cpp \
User/lib/utools/src/about_mang/about_mang.cpp \
User/lib/utools/src/coded/base64.cpp \
User/lib/utools/src/coded/crc.cpp \
User/lib/utools/src/coded/endian.cpp \
User/lib/utools/src/coded/hexstr.cpp \
User/lib/utools/src/coded/md5.cpp \
User/lib/utools/src/coded/sha1.cpp \
User/lib/utools/src/logger/logger.cpp \
User/lib/utools/src/ufmt/f_string.cpp \
User/lib/utools/src/umempool/mempool_ipml.cpp \
User/lib/utools/src/utime/time_configurator.cpp \
User/router/hu_entry.cpp \
build/main.cpp


# ASM sources
ASM_SOURCES =  \
startup_stm32h743xx.s



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
POSTFIX = "
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
GCC_PATH="C:/TOOLS/GCC-ARM-NONE-EABI/BIN
ifdef GCC_PATH
CXX = $(GCC_PATH)/$(PREFIX)g++$(POSTFIX)
CC = $(GCC_PATH)/$(PREFIX)gcc$(POSTFIX)
AS = $(GCC_PATH)/$(PREFIX)gcc$(POSTFIX) -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy$(POSTFIX)
SZ = $(GCC_PATH)/$(PREFIX)size$(POSTFIX)
else
CXX = $(PREFIX)g++
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32H743xx \
-DUSE_HAL_DRIVER


# CXX defines
CXX_DEFS =  \
-DSTM32H743xx \
-DUSE_HAL_DRIVER


# AS includes
AS_INCLUDES = \

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/CMSIS/Device/ST/STM32H7xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/STM32H7xx_HAL_Driver/Inc \
-IDrivers/STM32H7xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IUser \
-IUser/asset \
-IUser/config \
-IUser/config/lvgl \
-IUser/lib/lvgl \
-IUser/lib/lvgl/demos \
-IUser/lib/lvgl/demos/benchmark \
-IUser/lib/lvgl/demos/keypad_encoder \
-IUser/lib/lvgl/demos/music \
-IUser/lib/lvgl/demos/music/assets \
-IUser/lib/lvgl/demos/stress \
-IUser/lib/lvgl/demos/widgets \
-IUser/lib/lvgl/env_support/cmsis-pack \
-IUser/lib/lvgl/env_support/rt-thread \
-IUser/lib/lvgl/env_support/rt-thread/squareline/ui/lvgl \
-IUser/lib/lvgl/src \
-IUser/lib/lvgl/src/core \
-IUser/lib/lvgl/src/draw \
-IUser/lib/lvgl/src/draw/arm2d \
-IUser/lib/lvgl/src/draw/nxp/pxp \
-IUser/lib/lvgl/src/draw/nxp/vglite \
-IUser/lib/lvgl/src/draw/renesas \
-IUser/lib/lvgl/src/draw/sdl \
-IUser/lib/lvgl/src/draw/stm32_dma2d \
-IUser/lib/lvgl/src/draw/sw \
-IUser/lib/lvgl/src/draw/swm341_dma2d \
-IUser/lib/lvgl/src/extra \
-IUser/lib/lvgl/src/extra/layouts \
-IUser/lib/lvgl/src/extra/layouts/flex \
-IUser/lib/lvgl/src/extra/layouts/grid \
-IUser/lib/lvgl/src/extra/libs \
-IUser/lib/lvgl/src/extra/libs/bmp \
-IUser/lib/lvgl/src/extra/libs/ffmpeg \
-IUser/lib/lvgl/src/extra/libs/freetype \
-IUser/lib/lvgl/src/extra/libs/fsdrv \
-IUser/lib/lvgl/src/extra/libs/gif \
-IUser/lib/lvgl/src/extra/libs/png \
-IUser/lib/lvgl/src/extra/libs/qrcode \
-IUser/lib/lvgl/src/extra/libs/rlottie \
-IUser/lib/lvgl/src/extra/libs/sjpg \
-IUser/lib/lvgl/src/extra/libs/tiny_ttf \
-IUser/lib/lvgl/src/extra/others \
-IUser/lib/lvgl/src/extra/others/fragment \
-IUser/lib/lvgl/src/extra/others/gridnav \
-IUser/lib/lvgl/src/extra/others/ime \
-IUser/lib/lvgl/src/extra/others/imgfont \
-IUser/lib/lvgl/src/extra/others/monkey \
-IUser/lib/lvgl/src/extra/others/msg \
-IUser/lib/lvgl/src/extra/others/snapshot \
-IUser/lib/lvgl/src/extra/themes \
-IUser/lib/lvgl/src/extra/themes/basic \
-IUser/lib/lvgl/src/extra/themes/default \
-IUser/lib/lvgl/src/extra/themes/mono \
-IUser/lib/lvgl/src/extra/widgets \
-IUser/lib/lvgl/src/extra/widgets/animimg \
-IUser/lib/lvgl/src/extra/widgets/calendar \
-IUser/lib/lvgl/src/extra/widgets/chart \
-IUser/lib/lvgl/src/extra/widgets/colorwheel \
-IUser/lib/lvgl/src/extra/widgets/imgbtn \
-IUser/lib/lvgl/src/extra/widgets/keyboard \
-IUser/lib/lvgl/src/extra/widgets/led \
-IUser/lib/lvgl/src/extra/widgets/list \
-IUser/lib/lvgl/src/extra/widgets/menu \
-IUser/lib/lvgl/src/extra/widgets/meter \
-IUser/lib/lvgl/src/extra/widgets/msgbox \
-IUser/lib/lvgl/src/extra/widgets/span \
-IUser/lib/lvgl/src/extra/widgets/spinbox \
-IUser/lib/lvgl/src/extra/widgets/spinner \
-IUser/lib/lvgl/src/extra/widgets/tabview \
-IUser/lib/lvgl/src/extra/widgets/tileview \
-IUser/lib/lvgl/src/extra/widgets/win \
-IUser/lib/lvgl/src/font \
-IUser/lib/lvgl/src/hal \
-IUser/lib/lvgl/src/misc \
-IUser/lib/lvgl/src/widgets \
-IUser/lib/lvgl/tests/src \
-IUser/lib/lvgl/tests/unity \
-IUser/lib/sdcp/include \
-IUser/lib/simple_protocol/include \
-IUser/lib/ukeypad/include \
-IUser/lib/utools/src \
-IUser/lib/utools/src/about_mang \
-IUser/lib/utools/src/coded \
-IUser/lib/utools/src/collab \
-IUser/lib/utools/src/fliter \
-IUser/lib/utools/src/logger \
-IUser/lib/utools/src/pattern \
-IUser/lib/utools/src/ufmt \
-IUser/lib/utools/src/umath \
-IUser/lib/utools/src/umemory \
-IUser/lib/utools/src/umempool \
-IUser/lib/utools/src/utime \
-IUser/module/fzi_map \
-IUser/module/language \
-IUser/module/sensor_calibration \
-IUser/module/ui \
-IUser/peripheral \
-IUser/peripheral/abstract_if \
-IUser/peripheral/knob_dji \
-IUser/router \
-IUser/router/radio_comm



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CXXFLAGS = $(MCU) $(CXX_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -feliminate-unused-debug-types

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf -ggdb
CXXFLAGS += -g -gdwarf -ggdb
endif

# Add additional flags
CFLAGS += -Wall -fdata-sections -ffunction-sections -std=c18 
ASFLAGS += -Wall -fdata-sections -ffunction-sections 
CXXFLAGS += -fno-exceptions -fno-rtti -std=c++20 

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32H743IITx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = \


# Additional LD Flags from config file
ADDITIONALLDFLAGS = -Wl,--print-memory-usage -lstdc++ -specs=nano.specs 

LDFLAGS = $(MCU) $(ADDITIONALLDFLAGS) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of cpp program objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(CPP_SOURCES:.cpp=.o)))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))

# list of C objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

# list of ASM program objects
UPPER_CASE_ASM_SOURCES = $(filter %.S,$(ASM_SOURCES))
LOWER_CASE_ASM_SOURCES = $(filter %.s,$(ASM_SOURCES))

OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(UPPER_CASE_ASM_SOURCES:.S=.o)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(LOWER_CASE_ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.cpp STM32Make.make | $(BUILD_DIR) 
	$(CXX) -c $(CXXFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.cpp=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.cxx STM32Make.make | $(BUILD_DIR) 
	$(CXX) -c $(CXXFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.cxx=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.c STM32Make.make | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s STM32Make.make | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S STM32Make.make | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) STM32Make.make
	$(CXX) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#######################################
# flash
#######################################
flash: $(BUILD_DIR)/$(TARGET).elf
	"D:/KZC/STM32/H743II_LCD/TOOLCHAIN/OPENOCD_CH347/BIN/OPENOCD.EXE" -f ./openocd.cfg -c "program $(BUILD_DIR)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: $(BUILD_DIR)/$(TARGET).elf
	"D:/KZC/STM32/H743II_LCD/TOOLCHAIN/OPENOCD_CH347/BIN/OPENOCD.EXE" -f ./openocd.cfg -c "init; reset halt; stm32h7x mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	cmd /c rd /s /q $(BUILD_DIR)

#######################################
# custom makefile rules
#######################################


	
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***