// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: hand_unit_main_ctrl_menu

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Screen1_Panel1;
lv_obj_t * ui_Screen1_Image_signal;
lv_obj_t * ui_Screen1_Image_battery;
lv_obj_t * ui_Screen1_Image_ue;
lv_obj_t * ui_Screen1_Image_motor1;
lv_obj_t * ui_Screen1_Image_motor2;
lv_obj_t * ui_Screen1_Image_motor3;
lv_obj_t * ui_Screen1_list1;
lv_obj_t * ui_Screen1_Panel_Dial;
lv_obj_t * ui_Screen1_Label1;
lv_obj_t * ui_Screen1_Label2;
void ui_event_Screen1_Slider1(lv_event_t * e);
lv_obj_t * ui_Screen1_Slider1;
lv_obj_t * ui_Screen1_Iris;
lv_obj_t * ui_Screen1_Panel_percentage1;
lv_obj_t * ui_Screen1_Label8;
lv_obj_t * ui_Screen1_Label9;
lv_obj_t * ui_Screen1_Label_UE1;
lv_obj_t * ui_Screen1_Label_Company1;
lv_obj_t * ui_Screen1_list2;
lv_obj_t * ui_Screen1_Panel_Rocker;
lv_obj_t * ui_Screen1_Label_UP;
lv_obj_t * ui_Screen1_Label_Rocker;
void ui_event_Screen1_Slider2(lv_event_t * e);
lv_obj_t * ui_Screen1_Slider2;
lv_obj_t * ui_Screen1_lable_Zoom;
lv_obj_t * ui_Screen1_Panel_percentage2;
lv_obj_t * ui_Screen1_Label4;
lv_obj_t * ui_Screen1_Label5;
lv_obj_t * ui_Screen1_Label_UE2;
lv_obj_t * ui_Screen1_Label_Company2;
lv_obj_t * ui_Screen1_list3;
lv_obj_t * ui_Screen1_Panel_Knob;
lv_obj_t * ui_Screen1_Label_CCW;
lv_obj_t * ui_Screen1_Label_Knob;
void ui_event_Screen1_Slider3(lv_event_t * e);
lv_obj_t * ui_Screen1_Slider3;
lv_obj_t * ui_Screen1_lable_Focus;
lv_obj_t * ui_Screen1_Panel_percentage3;
lv_obj_t * ui_Screen1_Label7;
lv_obj_t * ui_Screen1_Label3;
lv_obj_t * ui_Screen1_Label_UE3;
lv_obj_t * ui_Screen1_Label_Company3;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Screen1_Panel2;
lv_obj_t * ui_Screen1_Image_signal1;
lv_obj_t * ui_Screen1_Image_battery1;
lv_obj_t * ui_Screen1_Image_ue1;
lv_obj_t * ui_Screen1_Image_motor4;
lv_obj_t * ui_Screen1_Image_motor5;
lv_obj_t * ui_Screen1_Image_motor6;
lv_obj_t * ui_Screen1_list4;
lv_obj_t * ui_Screen1_Panel_Dial1;
lv_obj_t * ui_Screen1_Label6;
lv_obj_t * ui_Screen1_Label10;
void ui_event_Screen1_Slider4(lv_event_t * e);
lv_obj_t * ui_Screen1_Slider4;
lv_obj_t * ui_Screen1_Iris1;
lv_obj_t * ui_Screen1_Panel_percentage4;
lv_obj_t * ui_Screen1_Label11;
lv_obj_t * ui_Screen1_Label12;
lv_obj_t * ui_Screen1_Label_UE4;
lv_obj_t * ui_Screen1_Label_Company4;
lv_obj_t * ui_Screen1_list5;
lv_obj_t * ui_Screen1_Panel_Rocker1;
lv_obj_t * ui_Screen1_Label_UP1;
lv_obj_t * ui_Screen1_Label_Rocker1;
void ui_event_Screen1_Slider5(lv_event_t * e);
lv_obj_t * ui_Screen1_Slider5;
lv_obj_t * ui_Screen1_lable_Zoom1;
lv_obj_t * ui_Screen1_Panel_percentage5;
lv_obj_t * ui_Screen1_Label13;
lv_obj_t * ui_Screen1_Label14;
lv_obj_t * ui_Screen1_Label_UE5;
lv_obj_t * ui_Screen1_Label_Company5;
lv_obj_t * ui_Screen1_list6;
lv_obj_t * ui_Screen1_Panel_Knob1;
lv_obj_t * ui_Screen1_Label_CCW1;
lv_obj_t * ui_Screen1_Label_Knob1;
void ui_event_Screen1_Slider6(lv_event_t * e);
lv_obj_t * ui_Screen1_Slider6;
lv_obj_t * ui_Screen1_lable_Focus1;
lv_obj_t * ui_Screen1_Panel_percentage6;
lv_obj_t * ui_Screen1_Label15;
lv_obj_t * ui_Screen1_Label16;
lv_obj_t * ui_Screen1_Label_UE6;
lv_obj_t * ui_Screen1_Label_Company6;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_battery[1] = {&ui_img_battery2_png};
const lv_img_dsc_t * ui_imgset_single[1] = {&ui_img_single6_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Screen1_Label8, target, "", "");
    }
}
void ui_event_Screen1_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Screen1_Label4, target, "", "");
    }
}
void ui_event_Screen1_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Screen1_Label7, target, "", "");
    }
}
void ui_event_Screen1_Slider4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Screen1_Label11, target, "", "");
    }
}
void ui_event_Screen1_Slider5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Screen1_Label13, target, "", "");
    }
}
void ui_event_Screen1_Slider6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Screen1_Label15, target, "", "");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
