// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: hand_unit_main_ctrl_menu

#ifndef _HAND_UNIT_MAIN_CTRL_MENU_UI_H
#define _HAND_UNIT_MAIN_CTRL_MENU_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen1_Panel1;
extern lv_obj_t * ui_Screen1_Image_signal;
extern lv_obj_t * ui_Screen1_Image_battery;
extern lv_obj_t * ui_Screen1_Image_ue;
extern lv_obj_t * ui_Screen1_Image_motor1;
extern lv_obj_t * ui_Screen1_Image_motor2;
extern lv_obj_t * ui_Screen1_Image_motor3;
extern lv_obj_t * ui_Screen1_list1;
extern lv_obj_t * ui_Screen1_Panel_Dial;
extern lv_obj_t * ui_Screen1_Label1;
extern lv_obj_t * ui_Screen1_Label2;
void ui_event_Screen1_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Slider1;
extern lv_obj_t * ui_Screen1_Iris;
extern lv_obj_t * ui_Screen1_Panel_percentage1;
extern lv_obj_t * ui_Screen1_Label8;
extern lv_obj_t * ui_Screen1_Label9;
extern lv_obj_t * ui_Screen1_Label_UE1;
extern lv_obj_t * ui_Screen1_Label_Company1;
extern lv_obj_t * ui_Screen1_list2;
extern lv_obj_t * ui_Screen1_Panel_Rocker;
extern lv_obj_t * ui_Screen1_Label_UP;
extern lv_obj_t * ui_Screen1_Label_Rocker;
void ui_event_Screen1_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Slider2;
extern lv_obj_t * ui_Screen1_lable_Zoom;
extern lv_obj_t * ui_Screen1_Panel_percentage2;
extern lv_obj_t * ui_Screen1_Label4;
extern lv_obj_t * ui_Screen1_Label5;
extern lv_obj_t * ui_Screen1_Label_UE2;
extern lv_obj_t * ui_Screen1_Label_Company2;
extern lv_obj_t * ui_Screen1_list3;
extern lv_obj_t * ui_Screen1_Panel_Knob;
extern lv_obj_t * ui_Screen1_Label_CCW;
extern lv_obj_t * ui_Screen1_Label_Knob;
void ui_event_Screen1_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Slider3;
extern lv_obj_t * ui_Screen1_lable_Focus;
extern lv_obj_t * ui_Screen1_Panel_percentage3;
extern lv_obj_t * ui_Screen1_Label7;
extern lv_obj_t * ui_Screen1_Label3;
extern lv_obj_t * ui_Screen1_Label_UE3;
extern lv_obj_t * ui_Screen1_Label_Company3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Screen1_Panel2;
extern lv_obj_t * ui_Screen1_Image_signal1;
extern lv_obj_t * ui_Screen1_Image_battery1;
extern lv_obj_t * ui_Screen1_Image_ue1;
extern lv_obj_t * ui_Screen1_Image_motor4;
extern lv_obj_t * ui_Screen1_Image_motor5;
extern lv_obj_t * ui_Screen1_Image_motor6;
extern lv_obj_t * ui_Screen1_list4;
extern lv_obj_t * ui_Screen1_Panel_Dial1;
extern lv_obj_t * ui_Screen1_Label6;
extern lv_obj_t * ui_Screen1_Label10;
void ui_event_Screen1_Slider4(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Slider4;
extern lv_obj_t * ui_Screen1_Iris1;
extern lv_obj_t * ui_Screen1_Panel_percentage4;
extern lv_obj_t * ui_Screen1_Label11;
extern lv_obj_t * ui_Screen1_Label12;
extern lv_obj_t * ui_Screen1_Label_UE4;
extern lv_obj_t * ui_Screen1_Label_Company4;
extern lv_obj_t * ui_Screen1_list5;
extern lv_obj_t * ui_Screen1_Panel_Rocker1;
extern lv_obj_t * ui_Screen1_Label_UP1;
extern lv_obj_t * ui_Screen1_Label_Rocker1;
void ui_event_Screen1_Slider5(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Slider5;
extern lv_obj_t * ui_Screen1_lable_Zoom1;
extern lv_obj_t * ui_Screen1_Panel_percentage5;
extern lv_obj_t * ui_Screen1_Label13;
extern lv_obj_t * ui_Screen1_Label14;
extern lv_obj_t * ui_Screen1_Label_UE5;
extern lv_obj_t * ui_Screen1_Label_Company5;
extern lv_obj_t * ui_Screen1_list6;
extern lv_obj_t * ui_Screen1_Panel_Knob1;
extern lv_obj_t * ui_Screen1_Label_CCW1;
extern lv_obj_t * ui_Screen1_Label_Knob1;
void ui_event_Screen1_Slider6(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Slider6;
extern lv_obj_t * ui_Screen1_lable_Focus1;
extern lv_obj_t * ui_Screen1_Panel_percentage6;
extern lv_obj_t * ui_Screen1_Label15;
extern lv_obj_t * ui_Screen1_Label16;
extern lv_obj_t * ui_Screen1_Label_UE6;
extern lv_obj_t * ui_Screen1_Label_Company6;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_single6_png);    // assets/single6.png
LV_IMG_DECLARE(ui_img_battery2_png);    // assets/Battery2.png
LV_IMG_DECLARE(ui_img_ue_png);    // assets/UE.png
LV_IMG_DECLARE(ui_img_motor_disconnected_png);    // assets/motor_disconnected.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
