// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: hand_unit_main_ctrl_menu

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Panel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen1_Panel2, 480);
    lv_obj_set_height(ui_Screen1_Panel2, 52);
    lv_obj_set_align(ui_Screen1_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Screen1_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Panel2, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel2, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Image_signal1 = lv_img_create(ui_Screen1_Panel2);
    lv_img_set_src(ui_Screen1_Image_signal1, &ui_img_single6_png);
    lv_obj_set_width(ui_Screen1_Image_signal1, 24);
    lv_obj_set_height(ui_Screen1_Image_signal1, 27);
    lv_obj_set_x(ui_Screen1_Image_signal1, lv_pct(-45));
    lv_obj_set_y(ui_Screen1_Image_signal1, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_signal1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_signal1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_signal1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_battery1 = lv_img_create(ui_Screen1_Panel2);
    lv_img_set_src(ui_Screen1_Image_battery1, &ui_img_battery2_png);
    lv_obj_set_width(ui_Screen1_Image_battery1, 24);
    lv_obj_set_height(ui_Screen1_Image_battery1, 27);
    lv_obj_set_x(ui_Screen1_Image_battery1, lv_pct(-35));
    lv_obj_set_y(ui_Screen1_Image_battery1, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_battery1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_battery1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_battery1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_ue1 = lv_img_create(ui_Screen1_Panel2);
    lv_img_set_src(ui_Screen1_Image_ue1, &ui_img_ue_png);
    lv_obj_set_width(ui_Screen1_Image_ue1, 24);
    lv_obj_set_height(ui_Screen1_Image_ue1, 27);
    lv_obj_set_x(ui_Screen1_Image_ue1, lv_pct(-25));
    lv_obj_set_y(ui_Screen1_Image_ue1, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_ue1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_ue1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_ue1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_motor4 = lv_img_create(ui_Screen1_Panel2);
    lv_img_set_src(ui_Screen1_Image_motor4, &ui_img_motor_disconnected_png);
    lv_obj_set_width(ui_Screen1_Image_motor4, 24);
    lv_obj_set_height(ui_Screen1_Image_motor4, 27);
    lv_obj_set_x(ui_Screen1_Image_motor4, lv_pct(25));
    lv_obj_set_y(ui_Screen1_Image_motor4, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_motor4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_motor4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_motor4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_motor5 = lv_img_create(ui_Screen1_Panel2);
    lv_img_set_src(ui_Screen1_Image_motor5, &ui_img_motor_disconnected_png);
    lv_obj_set_width(ui_Screen1_Image_motor5, 24);
    lv_obj_set_height(ui_Screen1_Image_motor5, 27);
    lv_obj_set_x(ui_Screen1_Image_motor5, lv_pct(35));
    lv_obj_set_y(ui_Screen1_Image_motor5, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_motor5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_motor5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_motor5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_motor6 = lv_img_create(ui_Screen1_Panel2);
    lv_img_set_src(ui_Screen1_Image_motor6, &ui_img_motor_disconnected_png);
    lv_obj_set_width(ui_Screen1_Image_motor6, 24);
    lv_obj_set_height(ui_Screen1_Image_motor6, 27);
    lv_obj_set_x(ui_Screen1_Image_motor6, lv_pct(45));
    lv_obj_set_y(ui_Screen1_Image_motor6, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_motor6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_motor6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_motor6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_list4 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen1_list4, 158);
    lv_obj_set_height(ui_Screen1_list4, 580);
    lv_obj_set_x(ui_Screen1_list4, -160);
    lv_obj_set_y(ui_Screen1_list4, 24);
    lv_obj_set_align(ui_Screen1_list4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_list4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_list4, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_list4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_list4, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_list4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_Dial1 = lv_obj_create(ui_Screen1_list4);
    lv_obj_set_width(ui_Screen1_Panel_Dial1, 158);
    lv_obj_set_height(ui_Screen1_Panel_Dial1, 50);
    lv_obj_set_x(ui_Screen1_Panel_Dial1, lv_pct(0));
    lv_obj_set_y(ui_Screen1_Panel_Dial1, lv_pct(-48));
    lv_obj_set_align(ui_Screen1_Panel_Dial1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_Panel_Dial1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_Dial1, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_Dial1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_Dial1, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_Dial1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label6 = lv_label_create(ui_Screen1_Panel_Dial1);
    lv_obj_set_width(ui_Screen1_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label6, 0);
    lv_obj_set_y(ui_Screen1_Label6, 10);
    lv_obj_set_align(ui_Screen1_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label6, "R");
    lv_obj_set_style_text_color(ui_Screen1_Label6, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label10 = lv_label_create(ui_Screen1_Panel_Dial1);
    lv_obj_set_width(ui_Screen1_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label10, 0);
    lv_obj_set_y(ui_Screen1_Label10, -10);
    lv_obj_set_align(ui_Screen1_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label10, "Dial");
    lv_obj_set_style_text_color(ui_Screen1_Label10, lv_color_hex(0x747480), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Slider4 = lv_slider_create(ui_Screen1_list4);
    lv_slider_set_value(ui_Screen1_Slider4, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Screen1_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Screen1_Slider4, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_Screen1_Slider4, 160);
    lv_obj_set_height(ui_Screen1_Slider4, 508);
    lv_obj_set_x(ui_Screen1_Slider4, 0);
    lv_obj_set_y(ui_Screen1_Slider4, 34);
    lv_obj_set_align(ui_Screen1_Slider4, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Screen1_Slider4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider4, lv_color_hex(0xA563E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider4, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Screen1_Slider4, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider4, lv_color_hex(0xA563E6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Screen1_Slider4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_Iris1 = lv_label_create(ui_Screen1_list4);
    lv_obj_set_width(ui_Screen1_Iris1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Iris1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Iris1, 0);
    lv_obj_set_y(ui_Screen1_Iris1, 200);
    lv_obj_set_align(ui_Screen1_Iris1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Iris1, "Iris");
    lv_obj_set_style_text_color(ui_Screen1_Iris1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Iris1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Iris1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Screen1_Iris1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_percentage4 = lv_obj_create(ui_Screen1_list4);
    lv_obj_set_width(ui_Screen1_Panel_percentage4, 105);
    lv_obj_set_height(ui_Screen1_Panel_percentage4, 50);
    lv_obj_set_align(ui_Screen1_Panel_percentage4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1_Panel_percentage4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1_Panel_percentage4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Screen1_Panel_percentage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_percentage4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_percentage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_percentage4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_percentage4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label11 = lv_label_create(ui_Screen1_Panel_percentage4);
    lv_obj_set_width(ui_Screen1_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label11, "50");
    lv_obj_set_style_text_color(ui_Screen1_Label11, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label11, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label12 = lv_label_create(ui_Screen1_Panel_percentage4);
    lv_obj_set_width(ui_Screen1_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label12, "%");
    lv_obj_set_style_text_font(ui_Screen1_Label12, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_UE4 = lv_label_create(ui_Screen1_list4);
    lv_obj_set_width(ui_Screen1_Label_UE4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_UE4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_UE4, 0);
    lv_obj_set_y(ui_Screen1_Label_UE4, -100);
    lv_obj_set_align(ui_Screen1_Label_UE4, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Screen1_Label_UE4, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Screen1_Label_UE4, "3.1415965");
    lv_obj_set_style_text_font(ui_Screen1_Label_UE4, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Company4 = lv_label_create(ui_Screen1_list4);
    lv_obj_set_width(ui_Screen1_Label_Company4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Company4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Company4, 0);
    lv_obj_set_y(ui_Screen1_Label_Company4, -50);
    lv_obj_set_align(ui_Screen1_Label_Company4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Company4, "T");
    lv_obj_set_style_text_font(ui_Screen1_Label_Company4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_list5 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen1_list5, 158);
    lv_obj_set_height(ui_Screen1_list5, 580);
    lv_obj_set_x(ui_Screen1_list5, 0);
    lv_obj_set_y(ui_Screen1_list5, 24);
    lv_obj_set_align(ui_Screen1_list5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_list5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_list5, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_list5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_list5, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_list5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_Rocker1 = lv_obj_create(ui_Screen1_list5);
    lv_obj_set_width(ui_Screen1_Panel_Rocker1, 158);
    lv_obj_set_height(ui_Screen1_Panel_Rocker1, 50);
    lv_obj_set_x(ui_Screen1_Panel_Rocker1, lv_pct(0));
    lv_obj_set_y(ui_Screen1_Panel_Rocker1, lv_pct(-48));
    lv_obj_set_align(ui_Screen1_Panel_Rocker1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_Panel_Rocker1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_Rocker1, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_Rocker1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_Rocker1, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_Rocker1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_UP1 = lv_label_create(ui_Screen1_Panel_Rocker1);
    lv_obj_set_width(ui_Screen1_Label_UP1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_UP1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_UP1, 0);
    lv_obj_set_y(ui_Screen1_Label_UP1, 10);
    lv_obj_set_align(ui_Screen1_Label_UP1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_UP1, "UP");
    lv_obj_set_style_text_color(ui_Screen1_Label_UP1, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_UP1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label_UP1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Rocker1 = lv_label_create(ui_Screen1_Panel_Rocker1);
    lv_obj_set_width(ui_Screen1_Label_Rocker1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Rocker1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Rocker1, 0);
    lv_obj_set_y(ui_Screen1_Label_Rocker1, -10);
    lv_obj_set_align(ui_Screen1_Label_Rocker1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Rocker1, "Rocker");
    lv_obj_set_style_text_color(ui_Screen1_Label_Rocker1, lv_color_hex(0x747480), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_Rocker1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Slider5 = lv_slider_create(ui_Screen1_list5);
    lv_slider_set_value(ui_Screen1_Slider5, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Screen1_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Screen1_Slider5, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_Screen1_Slider5, 160);
    lv_obj_set_height(ui_Screen1_Slider5, 508);
    lv_obj_set_x(ui_Screen1_Slider5, 0);
    lv_obj_set_y(ui_Screen1_Slider5, 34);
    lv_obj_set_align(ui_Screen1_Slider5, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Screen1_Slider5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider5, lv_color_hex(0xA563E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider5, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Screen1_Slider5, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider5, lv_color_hex(0xA563E6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Screen1_Slider5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_lable_Zoom1 = lv_label_create(ui_Screen1_list5);
    lv_obj_set_width(ui_Screen1_lable_Zoom1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_lable_Zoom1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_lable_Zoom1, 0);
    lv_obj_set_y(ui_Screen1_lable_Zoom1, 200);
    lv_obj_set_align(ui_Screen1_lable_Zoom1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_lable_Zoom1, "Zoom");
    lv_obj_set_style_text_color(ui_Screen1_lable_Zoom1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_lable_Zoom1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_lable_Zoom1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Screen1_lable_Zoom1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_percentage5 = lv_obj_create(ui_Screen1_list5);
    lv_obj_set_width(ui_Screen1_Panel_percentage5, 105);
    lv_obj_set_height(ui_Screen1_Panel_percentage5, 50);
    lv_obj_set_align(ui_Screen1_Panel_percentage5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1_Panel_percentage5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1_Panel_percentage5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Screen1_Panel_percentage5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_percentage5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_percentage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_percentage5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_percentage5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label13 = lv_label_create(ui_Screen1_Panel_percentage5);
    lv_obj_set_width(ui_Screen1_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label13, "50");
    lv_obj_set_style_text_color(ui_Screen1_Label13, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label13, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label14 = lv_label_create(ui_Screen1_Panel_percentage5);
    lv_obj_set_width(ui_Screen1_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label14, "%");
    lv_obj_set_style_text_font(ui_Screen1_Label14, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_UE5 = lv_label_create(ui_Screen1_list5);
    lv_obj_set_width(ui_Screen1_Label_UE5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_UE5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_UE5, 0);
    lv_obj_set_y(ui_Screen1_Label_UE5, -100);
    lv_obj_set_align(ui_Screen1_Label_UE5, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Screen1_Label_UE5, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Screen1_Label_UE5, "3.1415963");
    lv_obj_set_style_text_font(ui_Screen1_Label_UE5, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Company5 = lv_label_create(ui_Screen1_list5);
    lv_obj_set_width(ui_Screen1_Label_Company5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Company5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Company5, 0);
    lv_obj_set_y(ui_Screen1_Label_Company5, -50);
    lv_obj_set_align(ui_Screen1_Label_Company5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Company5, "mm");
    lv_obj_set_style_text_font(ui_Screen1_Label_Company5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_list6 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen1_list6, 158);
    lv_obj_set_height(ui_Screen1_list6, 580);
    lv_obj_set_x(ui_Screen1_list6, 160);
    lv_obj_set_y(ui_Screen1_list6, 24);
    lv_obj_set_align(ui_Screen1_list6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_list6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_list6, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_list6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_list6, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_list6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_Knob1 = lv_obj_create(ui_Screen1_list6);
    lv_obj_set_width(ui_Screen1_Panel_Knob1, 158);
    lv_obj_set_height(ui_Screen1_Panel_Knob1, 50);
    lv_obj_set_x(ui_Screen1_Panel_Knob1, lv_pct(0));
    lv_obj_set_y(ui_Screen1_Panel_Knob1, lv_pct(-48));
    lv_obj_set_align(ui_Screen1_Panel_Knob1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_Panel_Knob1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_Knob1, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_Knob1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_Knob1, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_Knob1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_CCW1 = lv_label_create(ui_Screen1_Panel_Knob1);
    lv_obj_set_width(ui_Screen1_Label_CCW1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_CCW1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_CCW1, 0);
    lv_obj_set_y(ui_Screen1_Label_CCW1, 10);
    lv_obj_set_align(ui_Screen1_Label_CCW1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_CCW1, "CCW");
    lv_obj_set_style_text_color(ui_Screen1_Label_CCW1, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_CCW1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label_CCW1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Knob1 = lv_label_create(ui_Screen1_Panel_Knob1);
    lv_obj_set_width(ui_Screen1_Label_Knob1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Knob1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Knob1, 0);
    lv_obj_set_y(ui_Screen1_Label_Knob1, -10);
    lv_obj_set_align(ui_Screen1_Label_Knob1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Knob1, "Knob");
    lv_obj_set_style_text_color(ui_Screen1_Label_Knob1, lv_color_hex(0x747480), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_Knob1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Slider6 = lv_slider_create(ui_Screen1_list6);
    lv_slider_set_value(ui_Screen1_Slider6, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Screen1_Slider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Screen1_Slider6, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_Screen1_Slider6, 160);
    lv_obj_set_height(ui_Screen1_Slider6, 508);
    lv_obj_set_x(ui_Screen1_Slider6, 0);
    lv_obj_set_y(ui_Screen1_Slider6, 34);
    lv_obj_set_align(ui_Screen1_Slider6, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Screen1_Slider6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider6, lv_color_hex(0xA563E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider6, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Screen1_Slider6, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider6, lv_color_hex(0xA563E6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Screen1_Slider6, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_lable_Focus1 = lv_label_create(ui_Screen1_list6);
    lv_obj_set_width(ui_Screen1_lable_Focus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_lable_Focus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_lable_Focus1, 0);
    lv_obj_set_y(ui_Screen1_lable_Focus1, 200);
    lv_obj_set_align(ui_Screen1_lable_Focus1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_lable_Focus1, "Focus");
    lv_obj_set_style_text_color(ui_Screen1_lable_Focus1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_lable_Focus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_lable_Focus1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Screen1_lable_Focus1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_percentage6 = lv_obj_create(ui_Screen1_list6);
    lv_obj_set_width(ui_Screen1_Panel_percentage6, 105);
    lv_obj_set_height(ui_Screen1_Panel_percentage6, 50);
    lv_obj_set_align(ui_Screen1_Panel_percentage6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1_Panel_percentage6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1_Panel_percentage6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Screen1_Panel_percentage6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_percentage6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_percentage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_percentage6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_percentage6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label15 = lv_label_create(ui_Screen1_Panel_percentage6);
    lv_obj_set_width(ui_Screen1_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label15, "50");
    lv_obj_set_style_text_color(ui_Screen1_Label15, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label15, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label16 = lv_label_create(ui_Screen1_Panel_percentage6);
    lv_obj_set_width(ui_Screen1_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label16, "%");
    lv_obj_set_style_text_font(ui_Screen1_Label16, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_UE6 = lv_label_create(ui_Screen1_list6);
    lv_obj_set_width(ui_Screen1_Label_UE6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_UE6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_UE6, 0);
    lv_obj_set_y(ui_Screen1_Label_UE6, -100);
    lv_obj_set_align(ui_Screen1_Label_UE6, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Screen1_Label_UE6, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Screen1_Label_UE6, "3.1415963");
    lv_obj_set_style_text_font(ui_Screen1_Label_UE6, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Company6 = lv_label_create(ui_Screen1_list6);
    lv_obj_set_width(ui_Screen1_Label_Company6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Company6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Company6, 0);
    lv_obj_set_y(ui_Screen1_Label_Company6, -50);
    lv_obj_set_align(ui_Screen1_Label_Company6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Company6, "m");
    lv_obj_set_style_text_font(ui_Screen1_Label_Company6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1_Slider4, ui_event_Screen1_Slider4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Slider5, ui_event_Screen1_Slider5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Slider6, ui_event_Screen1_Slider6, LV_EVENT_ALL, NULL);

}
