// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: hand_unit_main_ctrl_menu

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_Panel1, 480);
    lv_obj_set_height(ui_Screen1_Panel1, 52);
    lv_obj_set_align(ui_Screen1_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Screen1_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Panel1, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel1, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Image_signal = lv_img_create(ui_Screen1_Panel1);
    lv_img_set_src(ui_Screen1_Image_signal, &ui_img_single6_png);
    lv_obj_set_width(ui_Screen1_Image_signal, 24);
    lv_obj_set_height(ui_Screen1_Image_signal, 27);
    lv_obj_set_x(ui_Screen1_Image_signal, lv_pct(-45));
    lv_obj_set_y(ui_Screen1_Image_signal, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_signal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_signal, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_signal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_battery = lv_img_create(ui_Screen1_Panel1);
    lv_img_set_src(ui_Screen1_Image_battery, &ui_img_battery2_png);
    lv_obj_set_width(ui_Screen1_Image_battery, 24);
    lv_obj_set_height(ui_Screen1_Image_battery, 27);
    lv_obj_set_x(ui_Screen1_Image_battery, lv_pct(-35));
    lv_obj_set_y(ui_Screen1_Image_battery, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_battery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_battery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_ue = lv_img_create(ui_Screen1_Panel1);
    lv_img_set_src(ui_Screen1_Image_ue, &ui_img_ue_png);
    lv_obj_set_width(ui_Screen1_Image_ue, 24);
    lv_obj_set_height(ui_Screen1_Image_ue, 27);
    lv_obj_set_x(ui_Screen1_Image_ue, lv_pct(-25));
    lv_obj_set_y(ui_Screen1_Image_ue, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_ue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_ue, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_ue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_motor1 = lv_img_create(ui_Screen1_Panel1);
    lv_img_set_src(ui_Screen1_Image_motor1, &ui_img_motor_disconnected_png);
    lv_obj_set_width(ui_Screen1_Image_motor1, 24);
    lv_obj_set_height(ui_Screen1_Image_motor1, 27);
    lv_obj_set_x(ui_Screen1_Image_motor1, lv_pct(25));
    lv_obj_set_y(ui_Screen1_Image_motor1, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_motor1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_motor1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_motor1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_motor2 = lv_img_create(ui_Screen1_Panel1);
    lv_img_set_src(ui_Screen1_Image_motor2, &ui_img_motor_disconnected_png);
    lv_obj_set_width(ui_Screen1_Image_motor2, 24);
    lv_obj_set_height(ui_Screen1_Image_motor2, 27);
    lv_obj_set_x(ui_Screen1_Image_motor2, lv_pct(35));
    lv_obj_set_y(ui_Screen1_Image_motor2, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_motor2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_motor2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_motor2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_Image_motor3 = lv_img_create(ui_Screen1_Panel1);
    lv_img_set_src(ui_Screen1_Image_motor3, &ui_img_motor_disconnected_png);
    lv_obj_set_width(ui_Screen1_Image_motor3, 24);
    lv_obj_set_height(ui_Screen1_Image_motor3, 27);
    lv_obj_set_x(ui_Screen1_Image_motor3, lv_pct(45));
    lv_obj_set_y(ui_Screen1_Image_motor3, lv_pct(0));
    lv_obj_set_align(ui_Screen1_Image_motor3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1_Image_motor3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Screen1_Image_motor3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1_list1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_list1, 158);
    lv_obj_set_height(ui_Screen1_list1, 580);
    lv_obj_set_x(ui_Screen1_list1, -160);
    lv_obj_set_y(ui_Screen1_list1, 24);
    lv_obj_set_align(ui_Screen1_list1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_list1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_list1, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_list1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_list1, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_list1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_Dial = lv_obj_create(ui_Screen1_list1);
    lv_obj_set_width(ui_Screen1_Panel_Dial, 158);
    lv_obj_set_height(ui_Screen1_Panel_Dial, 50);
    lv_obj_set_x(ui_Screen1_Panel_Dial, lv_pct(0));
    lv_obj_set_y(ui_Screen1_Panel_Dial, lv_pct(-48));
    lv_obj_set_align(ui_Screen1_Panel_Dial, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_Panel_Dial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_Dial, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_Dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_Dial, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_Dial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label1 = lv_label_create(ui_Screen1_Panel_Dial);
    lv_obj_set_width(ui_Screen1_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label1, 0);
    lv_obj_set_y(ui_Screen1_Label1, 10);
    lv_obj_set_align(ui_Screen1_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label1, "R");
    lv_obj_set_style_text_color(ui_Screen1_Label1, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label2 = lv_label_create(ui_Screen1_Panel_Dial);
    lv_obj_set_width(ui_Screen1_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label2, 0);
    lv_obj_set_y(ui_Screen1_Label2, -10);
    lv_obj_set_align(ui_Screen1_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label2, "Dial");
    lv_obj_set_style_text_color(ui_Screen1_Label2, lv_color_hex(0x747480), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Slider1 = lv_slider_create(ui_Screen1_list1);
    lv_slider_set_value(ui_Screen1_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Screen1_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Screen1_Slider1, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_Screen1_Slider1, 160);
    lv_obj_set_height(ui_Screen1_Slider1, 508);
    lv_obj_set_x(ui_Screen1_Slider1, 0);
    lv_obj_set_y(ui_Screen1_Slider1, 34);
    lv_obj_set_align(ui_Screen1_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Screen1_Slider1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider1, lv_color_hex(0xA563E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Screen1_Slider1, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider1, lv_color_hex(0xA563E6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Screen1_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_Iris = lv_label_create(ui_Screen1_list1);
    lv_obj_set_width(ui_Screen1_Iris, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Iris, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Iris, 0);
    lv_obj_set_y(ui_Screen1_Iris, 200);
    lv_obj_set_align(ui_Screen1_Iris, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Iris, "Iris");
    lv_obj_set_style_text_color(ui_Screen1_Iris, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Iris, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Iris, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Screen1_Iris, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_percentage1 = lv_obj_create(ui_Screen1_list1);
    lv_obj_set_width(ui_Screen1_Panel_percentage1, 105);
    lv_obj_set_height(ui_Screen1_Panel_percentage1, 50);
    lv_obj_set_align(ui_Screen1_Panel_percentage1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1_Panel_percentage1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1_Panel_percentage1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Screen1_Panel_percentage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_percentage1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_percentage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_percentage1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_percentage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label8 = lv_label_create(ui_Screen1_Panel_percentage1);
    lv_obj_set_width(ui_Screen1_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label8, "50");
    lv_obj_set_style_text_color(ui_Screen1_Label8, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label8, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label9 = lv_label_create(ui_Screen1_Panel_percentage1);
    lv_obj_set_width(ui_Screen1_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label9, "%");
    lv_obj_set_style_text_font(ui_Screen1_Label9, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_UE1 = lv_label_create(ui_Screen1_list1);
    lv_obj_set_width(ui_Screen1_Label_UE1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_UE1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_UE1, 0);
    lv_obj_set_y(ui_Screen1_Label_UE1, -100);
    lv_obj_set_align(ui_Screen1_Label_UE1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Screen1_Label_UE1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Screen1_Label_UE1, "3.1415965");
    lv_obj_set_style_text_font(ui_Screen1_Label_UE1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Company1 = lv_label_create(ui_Screen1_list1);
    lv_obj_set_width(ui_Screen1_Label_Company1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Company1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Company1, 0);
    lv_obj_set_y(ui_Screen1_Label_Company1, -50);
    lv_obj_set_align(ui_Screen1_Label_Company1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Company1, "T");
    lv_obj_set_style_text_font(ui_Screen1_Label_Company1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_list2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_list2, 158);
    lv_obj_set_height(ui_Screen1_list2, 580);
    lv_obj_set_x(ui_Screen1_list2, 0);
    lv_obj_set_y(ui_Screen1_list2, 24);
    lv_obj_set_align(ui_Screen1_list2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_list2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_list2, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_list2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_list2, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_list2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_Rocker = lv_obj_create(ui_Screen1_list2);
    lv_obj_set_width(ui_Screen1_Panel_Rocker, 158);
    lv_obj_set_height(ui_Screen1_Panel_Rocker, 50);
    lv_obj_set_x(ui_Screen1_Panel_Rocker, lv_pct(0));
    lv_obj_set_y(ui_Screen1_Panel_Rocker, lv_pct(-48));
    lv_obj_set_align(ui_Screen1_Panel_Rocker, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_Panel_Rocker, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_Rocker, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_Rocker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_Rocker, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_Rocker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_UP = lv_label_create(ui_Screen1_Panel_Rocker);
    lv_obj_set_width(ui_Screen1_Label_UP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_UP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_UP, 0);
    lv_obj_set_y(ui_Screen1_Label_UP, 10);
    lv_obj_set_align(ui_Screen1_Label_UP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_UP, "UP");
    lv_obj_set_style_text_color(ui_Screen1_Label_UP, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_UP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label_UP, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Rocker = lv_label_create(ui_Screen1_Panel_Rocker);
    lv_obj_set_width(ui_Screen1_Label_Rocker, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Rocker, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Rocker, 0);
    lv_obj_set_y(ui_Screen1_Label_Rocker, -10);
    lv_obj_set_align(ui_Screen1_Label_Rocker, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Rocker, "Rocker");
    lv_obj_set_style_text_color(ui_Screen1_Label_Rocker, lv_color_hex(0x747480), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_Rocker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Slider2 = lv_slider_create(ui_Screen1_list2);
    lv_slider_set_value(ui_Screen1_Slider2, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Screen1_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Screen1_Slider2, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_Screen1_Slider2, 160);
    lv_obj_set_height(ui_Screen1_Slider2, 508);
    lv_obj_set_x(ui_Screen1_Slider2, 0);
    lv_obj_set_y(ui_Screen1_Slider2, 34);
    lv_obj_set_align(ui_Screen1_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Screen1_Slider2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider2, lv_color_hex(0xA563E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider2, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Screen1_Slider2, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider2, lv_color_hex(0xA563E6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Screen1_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_lable_Zoom = lv_label_create(ui_Screen1_list2);
    lv_obj_set_width(ui_Screen1_lable_Zoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_lable_Zoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_lable_Zoom, 0);
    lv_obj_set_y(ui_Screen1_lable_Zoom, 200);
    lv_obj_set_align(ui_Screen1_lable_Zoom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_lable_Zoom, "Zoom");
    lv_obj_set_style_text_color(ui_Screen1_lable_Zoom, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_lable_Zoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_lable_Zoom, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Screen1_lable_Zoom, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_percentage2 = lv_obj_create(ui_Screen1_list2);
    lv_obj_set_width(ui_Screen1_Panel_percentage2, 105);
    lv_obj_set_height(ui_Screen1_Panel_percentage2, 50);
    lv_obj_set_align(ui_Screen1_Panel_percentage2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1_Panel_percentage2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1_Panel_percentage2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Screen1_Panel_percentage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_percentage2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_percentage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_percentage2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_percentage2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label4 = lv_label_create(ui_Screen1_Panel_percentage2);
    lv_obj_set_width(ui_Screen1_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label4, "50");
    lv_obj_set_style_text_color(ui_Screen1_Label4, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label5 = lv_label_create(ui_Screen1_Panel_percentage2);
    lv_obj_set_width(ui_Screen1_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label5, "%");
    lv_obj_set_style_text_font(ui_Screen1_Label5, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_UE2 = lv_label_create(ui_Screen1_list2);
    lv_obj_set_width(ui_Screen1_Label_UE2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_UE2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_UE2, 0);
    lv_obj_set_y(ui_Screen1_Label_UE2, -100);
    lv_obj_set_align(ui_Screen1_Label_UE2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Screen1_Label_UE2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Screen1_Label_UE2, "3.1415963");
    lv_obj_set_style_text_font(ui_Screen1_Label_UE2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Company2 = lv_label_create(ui_Screen1_list2);
    lv_obj_set_width(ui_Screen1_Label_Company2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Company2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Company2, 0);
    lv_obj_set_y(ui_Screen1_Label_Company2, -50);
    lv_obj_set_align(ui_Screen1_Label_Company2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Company2, "mm");
    lv_obj_set_style_text_font(ui_Screen1_Label_Company2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_list3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1_list3, 158);
    lv_obj_set_height(ui_Screen1_list3, 580);
    lv_obj_set_x(ui_Screen1_list3, 160);
    lv_obj_set_y(ui_Screen1_list3, 24);
    lv_obj_set_align(ui_Screen1_list3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_list3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_list3, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_list3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_list3, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_list3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_Knob = lv_obj_create(ui_Screen1_list3);
    lv_obj_set_width(ui_Screen1_Panel_Knob, 158);
    lv_obj_set_height(ui_Screen1_Panel_Knob, 50);
    lv_obj_set_x(ui_Screen1_Panel_Knob, lv_pct(0));
    lv_obj_set_y(ui_Screen1_Panel_Knob, lv_pct(-48));
    lv_obj_set_align(ui_Screen1_Panel_Knob, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1_Panel_Knob, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_Knob, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_Knob, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_Knob, lv_color_hex(0x1C1C1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_Knob, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_CCW = lv_label_create(ui_Screen1_Panel_Knob);
    lv_obj_set_width(ui_Screen1_Label_CCW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_CCW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_CCW, 0);
    lv_obj_set_y(ui_Screen1_Label_CCW, 10);
    lv_obj_set_align(ui_Screen1_Label_CCW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_CCW, "CCW");
    lv_obj_set_style_text_color(ui_Screen1_Label_CCW, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_CCW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label_CCW, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Knob = lv_label_create(ui_Screen1_Panel_Knob);
    lv_obj_set_width(ui_Screen1_Label_Knob, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Knob, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Knob, 0);
    lv_obj_set_y(ui_Screen1_Label_Knob, -10);
    lv_obj_set_align(ui_Screen1_Label_Knob, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Knob, "Knob");
    lv_obj_set_style_text_color(ui_Screen1_Label_Knob, lv_color_hex(0x747480), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label_Knob, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Slider3 = lv_slider_create(ui_Screen1_list3);
    lv_slider_set_value(ui_Screen1_Slider3, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Screen1_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Screen1_Slider3, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_Screen1_Slider3, 160);
    lv_obj_set_height(ui_Screen1_Slider3, 508);
    lv_obj_set_x(ui_Screen1_Slider3, 0);
    lv_obj_set_y(ui_Screen1_Slider3, 34);
    lv_obj_set_align(ui_Screen1_Slider3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Screen1_Slider3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider3, lv_color_hex(0xA563E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider3, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Screen1_Slider3, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1_Slider3, lv_color_hex(0xA563E6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Slider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Screen1_Slider3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Screen1_lable_Focus = lv_label_create(ui_Screen1_list3);
    lv_obj_set_width(ui_Screen1_lable_Focus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_lable_Focus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_lable_Focus, 0);
    lv_obj_set_y(ui_Screen1_lable_Focus, 200);
    lv_obj_set_align(ui_Screen1_lable_Focus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_lable_Focus, "Focus");
    lv_obj_set_style_text_color(ui_Screen1_lable_Focus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_lable_Focus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_lable_Focus, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Screen1_lable_Focus, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Panel_percentage3 = lv_obj_create(ui_Screen1_list3);
    lv_obj_set_width(ui_Screen1_Panel_percentage3, 105);
    lv_obj_set_height(ui_Screen1_Panel_percentage3, 50);
    lv_obj_set_align(ui_Screen1_Panel_percentage3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1_Panel_percentage3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1_Panel_percentage3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Screen1_Panel_percentage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1_Panel_percentage3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1_Panel_percentage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen1_Panel_percentage3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen1_Panel_percentage3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label7 = lv_label_create(ui_Screen1_Panel_percentage3);
    lv_obj_set_width(ui_Screen1_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label7, "50");
    lv_obj_set_style_text_color(ui_Screen1_Label7, lv_color_hex(0xD1D1E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1_Label7, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label3 = lv_label_create(ui_Screen1_Panel_percentage3);
    lv_obj_set_width(ui_Screen1_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label3, "%");
    lv_obj_set_style_text_font(ui_Screen1_Label3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_UE3 = lv_label_create(ui_Screen1_list3);
    lv_obj_set_width(ui_Screen1_Label_UE3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_UE3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_UE3, 0);
    lv_obj_set_y(ui_Screen1_Label_UE3, -100);
    lv_obj_set_align(ui_Screen1_Label_UE3, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Screen1_Label_UE3, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Screen1_Label_UE3, "3.1415963");
    lv_obj_set_style_text_font(ui_Screen1_Label_UE3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1_Label_Company3 = lv_label_create(ui_Screen1_list3);
    lv_obj_set_width(ui_Screen1_Label_Company3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1_Label_Company3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen1_Label_Company3, 0);
    lv_obj_set_y(ui_Screen1_Label_Company3, -50);
    lv_obj_set_align(ui_Screen1_Label_Company3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1_Label_Company3, "m");
    lv_obj_set_style_text_font(ui_Screen1_Label_Company3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1_Slider1, ui_event_Screen1_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Slider2, ui_event_Screen1_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1_Slider3, ui_event_Screen1_Slider3, LV_EVENT_ALL, NULL);

}
